/**
 * RESONATE — Collections Page.
 * Smart collection kits generated by the RPM AI engine.
 * Displays collection cards in a grid layout.
 */

import { memo } from "react";
import { useTheme } from "../theme/ThemeProvider";
import { SERIF, MONO, AF } from "../theme/fonts";
import { SmartCollection } from "../components/SmartCollection";

export const CollectionsPage = memo(function CollectionsPage({
  collections, audio, onPlay, api,
}) {
  const { theme, mode } = useTheme();
  const isDark = mode === "dark";

  const nonEmpty = (collections || []).filter(c => c.samples?.length > 0);

  return (
    <div style={{ flex: 1, overflowY: "auto", padding: 24 }}>
      <div style={{ marginBottom: 24 }}>
        <h2 style={{
          fontSize: 20, fontWeight: 300, color: theme.text,
          fontFamily: SERIF, letterSpacing: -0.5, margin: "0 0 6px",
        }}>Collections</h2>
        <p style={{ fontSize: 11, color: theme.textMuted, fontFamily: AF, margin: 0 }}>
          AI-curated sample kits based on your analysis
        </p>
      </div>

      {nonEmpty.length === 0 ? (
        <div style={{
          padding: 60, textAlign: "center", color: theme.textMuted,
          fontSize: 12, fontFamily: AF,
        }}>
          <div style={{ fontSize: 32, marginBottom: 12, opacity: 0.3 }}>
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round">
              <rect x="3" y="3" width="7" height="7" /><rect x="14" y="3" width="7" height="7" />
              <rect x="3" y="14" width="7" height="7" /><rect x="14" y="14" width="7" height="7" />
            </svg>
          </div>
          Upload a track to generate smart collections
        </div>
      ) : (
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
          gap: 16,
        }}>
          {nonEmpty.map(c => (
            <SmartCollection
              key={c.id}
              collection={c}
              onPreview={(sample) => {
                if (sample.filepath) {
                  const s = { path: sample.filepath, id: sample.filepath, name: sample.name };
                  onPlay?.(s);
                }
              }}
              onExport={(collectionId) => api?.exportCollection(collectionId)}
            />
          ))}
        </div>
      )}
    </div>
  );
});
