"""
RESONATE Production Model — Phase E: Contrastive Text-Audio Pre-Training

Downloads, processes, and serves text-audio pairs for contrastive learning.
The model learns to connect sound to language — understanding *why* things
sound the way they do, not just classifying them.

Data sources (all free):
  - WavCaps:       403k audio clips with natural language captions
  - LP-MusicCaps:  500k+ music clips with LLM-generated captions
  - MusicCaps:     5.5k expert-written music descriptions (Google)
  - AudioSet:      2M+ 10-sec YouTube clips with 527 event labels
  - Freesound:     500k+ community sounds with text tags

Total: ~3M+ text-audio pairs, all free.
"""
from __future__ import annotations

import csv
import json
import logging
import os
import sqlite3
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import requests
from tqdm import tqdm

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_DATA_ROOT = Path.home() / ".resonate" / "datasets" / "phase_e"

WAVCAPS_URLS = {
    # WavCaps metadata JSONs (audio is referenced by URL)
    "freesound": "https://huggingface.co/datasets/cvssp/WavCaps/resolve/main/json_files/FreeSound/fsd_final.json",
    "bbc": "https://huggingface.co/datasets/cvssp/WavCaps/resolve/main/json_files/BBC_Sound_Effects/bbc_final.json",
    "soundbible": "https://huggingface.co/datasets/cvssp/WavCaps/resolve/main/json_files/SoundBible/sb_final.json",
    "audioset_sl": "https://huggingface.co/datasets/cvssp/WavCaps/resolve/main/json_files/AudioSet_SL/as_final.json",
}

LP_MUSICCAPS_URL = "https://huggingface.co/datasets/seungheondoh/LP-MusicCaps-MSD/resolve/main/data"
MUSICCAPS_URL = "https://huggingface.co/datasets/google/MusicCaps/resolve/main/musiccaps-public.csv"

AUDIOSET_ONTOLOGY_URL = "https://raw.githubusercontent.com/audioset/ontology/master/ontology.json"
AUDIOSET_CSV_URLS = {
    "balanced_train": "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/balanced_train_segments.csv",
    "eval": "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/eval_segments.csv",
    "unbalanced_train": "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/unbalanced_train_segments.csv",
}


@dataclass
class TextAudioPair:
    """A single text-audio training pair for contrastive learning."""
    audio_path: str
    caption: str
    source: str  # wavcaps, musiccaps, lp_musiccaps, audioset, freesound
    audio_url: Optional[str] = None
    duration: float = 0.0
    tags: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# WavCaps Downloader (403k pairs)
# ---------------------------------------------------------------------------

class WavCapsDownloader:
    """
    Downloads WavCaps dataset — 403k audio clips with natural language captions.
    Captions generated by ChatGPT from existing audio metadata, then filtered.
    """

    def __init__(self, data_root: Path = DEFAULT_DATA_ROOT):
        self.data_dir = data_root / "wavcaps"
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self._session = requests.Session()

    def download_metadata(self) -> dict[str, list[dict]]:
        """Download all WavCaps metadata JSON files."""
        all_metadata = {}

        for source_name, url in WAVCAPS_URLS.items():
            json_path = self.data_dir / f"{source_name}.json"

            if json_path.exists():
                logger.info(f"  WavCaps {source_name}: already downloaded")
                with open(json_path) as f:
                    all_metadata[source_name] = json.load(f)["data"]
                continue

            logger.info(f"  Downloading WavCaps {source_name} metadata...")
            resp = self._session.get(url, timeout=60)
            resp.raise_for_status()

            with open(json_path, "wb") as f:
                f.write(resp.content)

            data = resp.json()
            all_metadata[source_name] = data.get("data", data)
            logger.info(f"    {len(all_metadata[source_name]):,} entries")

        return all_metadata

    def download_audio(self, metadata: dict[str, list[dict]], max_per_source: int = 0) -> list[TextAudioPair]:
        """Download audio files from WavCaps metadata."""
        pairs = []
        audio_dir = self.data_dir / "audio"
        audio_dir.mkdir(exist_ok=True)

        for source_name, entries in metadata.items():
            source_dir = audio_dir / source_name
            source_dir.mkdir(exist_ok=True)

            items = entries[:max_per_source] if max_per_source > 0 else entries
            downloaded = 0

            for entry in tqdm(items, desc=f"WavCaps/{source_name}", unit="clip"):
                # Each entry has: id, caption, audio (URL or path), duration
                caption = entry.get("caption", "")
                audio_url = entry.get("download_link") or entry.get("audio", "")
                entry_id = entry.get("id", str(hash(caption)))[:32]
                duration = entry.get("duration", 0)

                if not audio_url or not caption:
                    continue

                # Determine file extension
                ext = ".flac" if ".flac" in audio_url else ".wav" if ".wav" in audio_url else ".mp3"
                audio_path = source_dir / f"{entry_id}{ext}"

                if not audio_path.exists():
                    try:
                        resp = self._session.get(audio_url, timeout=30)
                        if resp.status_code == 200:
                            audio_path.write_bytes(resp.content)
                            downloaded += 1
                        time.sleep(0.05)  # be nice to servers
                    except Exception as e:
                        logger.debug(f"Failed to download {entry_id}: {e}")
                        continue

                if audio_path.exists():
                    pairs.append(TextAudioPair(
                        audio_path=str(audio_path),
                        caption=caption,
                        source=f"wavcaps_{source_name}",
                        audio_url=audio_url,
                        duration=duration,
                    ))

            logger.info(f"  WavCaps/{source_name}: {len(pairs):,} pairs ({downloaded} newly downloaded)")

        return pairs


# ---------------------------------------------------------------------------
# MusicCaps Downloader (5.5k expert pairs)
# ---------------------------------------------------------------------------

class MusicCapsDownloader:
    """
    Downloads Google's MusicCaps — 5,521 expert-written music descriptions.
    Each clip is 10 seconds from YouTube with a detailed natural language caption.
    """

    def __init__(self, data_root: Path = DEFAULT_DATA_ROOT):
        self.data_dir = data_root / "musiccaps"
        self.data_dir.mkdir(parents=True, exist_ok=True)

    def download_metadata(self) -> list[dict]:
        """Download MusicCaps CSV from HuggingFace."""
        csv_path = self.data_dir / "musiccaps-public.csv"

        if not csv_path.exists():
            logger.info("  Downloading MusicCaps metadata...")
            resp = requests.get(MUSICCAPS_URL, timeout=60)
            resp.raise_for_status()
            csv_path.write_bytes(resp.content)

        entries = []
        with open(csv_path, newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                entries.append(row)

        logger.info(f"  MusicCaps: {len(entries):,} entries")
        return entries

    def download_audio(self, entries: list[dict], max_entries: int = 0) -> list[TextAudioPair]:
        """
        Download audio from YouTube using yt-dlp.
        Each entry has: ytid, start_s, end_s, caption, aspect_list, audioset_positive_labels
        """
        audio_dir = self.data_dir / "audio"
        audio_dir.mkdir(exist_ok=True)
        pairs = []

        items = entries[:max_entries] if max_entries > 0 else entries

        for entry in tqdm(items, desc="MusicCaps", unit="clip"):
            ytid = entry.get("ytid", "")
            start_s = float(entry.get("start_s", 0))
            end_s = float(entry.get("end_s", 10))
            caption = entry.get("caption", "")
            tags = [t.strip() for t in entry.get("aspect_list", "").strip("[]").split(",") if t.strip()]

            if not ytid or not caption:
                continue

            audio_path = audio_dir / f"{ytid}_{int(start_s)}_{int(end_s)}.wav"

            if not audio_path.exists():
                try:
                    url = f"https://www.youtube.com/watch?v={ytid}"
                    cmd = [
                        "yt-dlp", "--quiet", "--no-warnings",
                        "--extract-audio", "--audio-format", "wav",
                        "--postprocessor-args", f"-ss {start_s} -to {end_s}",
                        "-o", str(audio_path),
                        url,
                    ]
                    result = subprocess.run(cmd, capture_output=True, timeout=60)
                    if result.returncode != 0:
                        continue
                except Exception:
                    continue

            if audio_path.exists():
                pairs.append(TextAudioPair(
                    audio_path=str(audio_path),
                    caption=caption,
                    source="musiccaps",
                    duration=end_s - start_s,
                    tags=tags,
                ))

        logger.info(f"  MusicCaps: {len(pairs):,} text-audio pairs downloaded")
        return pairs


# ---------------------------------------------------------------------------
# LP-MusicCaps Downloader (500k+ LLM-generated captions)
# ---------------------------------------------------------------------------

class LPMusicCapsDownloader:
    """
    Downloads LP-MusicCaps — 500k+ music clips with LLM-generated captions.
    Built on the Million Song Dataset with pseudo-captions from LLMs.
    """

    def __init__(self, data_root: Path = DEFAULT_DATA_ROOT):
        self.data_dir = data_root / "lp_musiccaps"
        self.data_dir.mkdir(parents=True, exist_ok=True)

    def download_metadata(self) -> list[dict]:
        """Download LP-MusicCaps metadata from HuggingFace."""
        meta_path = self.data_dir / "metadata.jsonl"

        if not meta_path.exists():
            logger.info("  Downloading LP-MusicCaps metadata...")
            # LP-MusicCaps is distributed as parquet files on HuggingFace
            try:
                from datasets import load_dataset
                ds = load_dataset("seungheondoh/LP-MusicCaps-MSD", split="train")
                entries = [dict(row) for row in ds]

                with open(meta_path, "w") as f:
                    for entry in entries:
                        f.write(json.dumps(entry) + "\n")

                logger.info(f"  LP-MusicCaps: {len(entries):,} entries")
                return entries

            except ImportError:
                logger.warning("  'datasets' library not installed — install with: pip install datasets")
                logger.info("  Attempting direct download...")

                # Fallback: download parquet files directly
                for split_idx in range(10):
                    url = f"{LP_MUSICCAPS_URL}/train-{split_idx:05d}-of-00010.parquet"
                    parquet_path = self.data_dir / f"train-{split_idx:05d}.parquet"
                    if not parquet_path.exists():
                        try:
                            resp = requests.get(url, timeout=120)
                            if resp.status_code == 200:
                                parquet_path.write_bytes(resp.content)
                        except Exception as e:
                            logger.warning(f"  Failed to download split {split_idx}: {e}")
                            break

                return []

        entries = []
        with open(meta_path) as f:
            for line in f:
                entries.append(json.loads(line))
        logger.info(f"  LP-MusicCaps: {len(entries):,} entries loaded from cache")
        return entries

    def build_pairs(self, entries: list[dict]) -> list[TextAudioPair]:
        """Build text-audio pairs from LP-MusicCaps metadata.
        Note: Audio must be sourced separately (7digital previews or user-provided).
        """
        pairs = []
        for entry in entries:
            caption = entry.get("caption", "") or entry.get("pseudo_caption", "")
            track_id = entry.get("track_id", "") or entry.get("id", "")

            if not caption:
                continue

            pairs.append(TextAudioPair(
                audio_path="",  # Resolved at training time
                caption=caption,
                source="lp_musiccaps",
                tags=entry.get("tags", []),
            ))

        logger.info(f"  LP-MusicCaps: {len(pairs):,} caption pairs (audio resolved at train time)")
        return pairs


# ---------------------------------------------------------------------------
# AudioSet Downloader (2M+ clips)
# ---------------------------------------------------------------------------

class AudioSetDownloader:
    """
    Downloads AudioSet metadata and ontology.
    Audio must be fetched from YouTube (yt-dlp required).
    527 sound event classes, 2M+ 10-second clips.
    """

    def __init__(self, data_root: Path = DEFAULT_DATA_ROOT):
        self.data_dir = data_root / "audioset"
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self._ontology: dict[str, str] = {}

    def download_ontology(self) -> dict[str, str]:
        """Download AudioSet ontology (label ID → human-readable name)."""
        ontology_path = self.data_dir / "ontology.json"

        if not ontology_path.exists():
            logger.info("  Downloading AudioSet ontology...")
            resp = requests.get(AUDIOSET_ONTOLOGY_URL, timeout=30)
            resp.raise_for_status()
            ontology_path.write_bytes(resp.content)

        with open(ontology_path) as f:
            ontology = json.load(f)

        self._ontology = {item["id"]: item["name"] for item in ontology}
        logger.info(f"  AudioSet ontology: {len(self._ontology)} classes")
        return self._ontology

    def download_segment_csvs(self) -> dict[str, list[dict]]:
        """Download AudioSet segment CSV files (balanced train, eval, unbalanced)."""
        all_segments = {}

        for split_name, url in AUDIOSET_CSV_URLS.items():
            csv_path = self.data_dir / f"{split_name}_segments.csv"

            if not csv_path.exists():
                logger.info(f"  Downloading AudioSet {split_name} segments...")
                resp = requests.get(url, timeout=120)
                resp.raise_for_status()
                csv_path.write_bytes(resp.content)

            # Parse CSV (first 3 lines are comments)
            segments = []
            with open(csv_path) as f:
                for line in f:
                    if line.startswith("#") or not line.strip():
                        continue
                    parts = line.strip().split(", ")
                    if len(parts) >= 4:
                        ytid = parts[0].strip()
                        start = float(parts[1].strip())
                        end = float(parts[2].strip())
                        label_ids = [lid.strip().strip('"') for lid in parts[3:]]
                        segments.append({
                            "ytid": ytid,
                            "start": start,
                            "end": end,
                            "label_ids": label_ids,
                        })

            all_segments[split_name] = segments
            logger.info(f"  AudioSet {split_name}: {len(segments):,} segments")

        return all_segments

    def segments_to_pairs(self, segments: dict[str, list[dict]]) -> list[TextAudioPair]:
        """Convert AudioSet segments to text-audio pairs using ontology labels."""
        if not self._ontology:
            self.download_ontology()

        pairs = []
        for split_name, split_segments in segments.items():
            for seg in split_segments:
                label_names = [self._ontology.get(lid, lid) for lid in seg["label_ids"]]
                # Create natural language caption from labels
                if len(label_names) == 1:
                    caption = f"A sound of {label_names[0].lower()}"
                elif len(label_names) == 2:
                    caption = f"A sound containing {label_names[0].lower()} and {label_names[1].lower()}"
                else:
                    caption = f"A sound containing {', '.join(l.lower() for l in label_names[:-1])}, and {label_names[-1].lower()}"

                pairs.append(TextAudioPair(
                    audio_path="",  # Downloaded on-demand via yt-dlp
                    caption=caption,
                    source=f"audioset_{split_name}",
                    audio_url=f"https://www.youtube.com/watch?v={seg['ytid']}",
                    duration=seg["end"] - seg["start"],
                    tags=label_names,
                ))

        logger.info(f"  AudioSet total: {len(pairs):,} text-audio pairs")
        return pairs

    def download_audio_batch(
        self, pairs: list[TextAudioPair], max_clips: int = 50000, workers: int = 4
    ) -> list[TextAudioPair]:
        """Download audio for a batch of AudioSet pairs using yt-dlp."""
        audio_dir = self.data_dir / "audio"
        audio_dir.mkdir(exist_ok=True)

        downloaded = []
        items = pairs[:max_clips] if max_clips > 0 else pairs

        for pair in tqdm(items, desc="AudioSet audio", unit="clip"):
            if not pair.audio_url:
                continue

            ytid = pair.audio_url.split("v=")[-1]
            audio_path = audio_dir / f"{ytid}.wav"

            if audio_path.exists():
                pair.audio_path = str(audio_path)
                downloaded.append(pair)
                continue

            try:
                cmd = [
                    "yt-dlp", "--quiet", "--no-warnings",
                    "--extract-audio", "--audio-format", "wav",
                    "--postprocessor-args", f"-ss {pair.duration} -t 10",
                    "-o", str(audio_path),
                    pair.audio_url,
                ]
                result = subprocess.run(cmd, capture_output=True, timeout=60)
                if result.returncode == 0 and audio_path.exists():
                    pair.audio_path = str(audio_path)
                    downloaded.append(pair)
            except Exception:
                continue

        logger.info(f"  AudioSet: {len(downloaded):,} clips downloaded")
        return downloaded


# ---------------------------------------------------------------------------
# Freesound Downloader (500k+)
# ---------------------------------------------------------------------------

class FreesoundDownloader:
    """
    Downloads from Freesound API — 500k+ user-uploaded sounds with text tags.
    Requires a Freesound API key (free registration).
    """

    API_BASE = "https://freesound.org/apiv2"

    def __init__(self, api_key: str, data_root: Path = DEFAULT_DATA_ROOT):
        self.api_key = api_key
        self.data_dir = data_root / "freesound"
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self._session = requests.Session()

    def search_sounds(
        self, query: str = "", filter_str: str = "", page_size: int = 150, max_pages: int = 100
    ) -> list[dict]:
        """Search Freesound for sounds matching query/filter."""
        results = []
        page = 1

        while page <= max_pages:
            params = {
                "token": self.api_key,
                "page_size": page_size,
                "page": page,
                "fields": "id,name,tags,description,duration,previews,avg_rating,num_ratings",
            }
            if query:
                params["query"] = query
            if filter_str:
                params["filter"] = filter_str

            try:
                resp = self._session.get(f"{self.API_BASE}/search/text/", params=params, timeout=30)
                if resp.status_code != 200:
                    break
                data = resp.json()
                results.extend(data.get("results", []))

                if not data.get("next"):
                    break
                page += 1
                time.sleep(0.1)
            except Exception as e:
                logger.warning(f"Freesound search error: {e}")
                break

        logger.info(f"  Freesound search '{query}': {len(results):,} results")
        return results

    def download_sounds(self, sounds: list[dict], max_sounds: int = 0) -> list[TextAudioPair]:
        """Download audio previews and build text-audio pairs."""
        audio_dir = self.data_dir / "audio"
        audio_dir.mkdir(exist_ok=True)
        pairs = []

        items = sounds[:max_sounds] if max_sounds > 0 else sounds

        for sound in tqdm(items, desc="Freesound", unit="sound"):
            sound_id = sound.get("id")
            name = sound.get("name", "")
            description = sound.get("description", "")
            tags = sound.get("tags", [])
            duration = sound.get("duration", 0)
            previews = sound.get("previews", {})

            # Build caption from name + description + tags
            caption = description if description else name
            if tags and len(caption) < 20:
                caption = f"{name}: {', '.join(tags[:5])}"

            # Download preview (HQ MP3 or OGG)
            preview_url = previews.get("preview-hq-mp3") or previews.get("preview-hq-ogg")
            if not preview_url:
                continue

            ext = ".mp3" if "mp3" in preview_url else ".ogg"
            audio_path = audio_dir / f"{sound_id}{ext}"

            if not audio_path.exists():
                try:
                    resp = self._session.get(preview_url, timeout=30)
                    if resp.status_code == 200:
                        audio_path.write_bytes(resp.content)
                    time.sleep(0.05)
                except Exception:
                    continue

            if audio_path.exists():
                pairs.append(TextAudioPair(
                    audio_path=str(audio_path),
                    caption=caption,
                    source="freesound",
                    duration=duration,
                    tags=tags,
                ))

        logger.info(f"  Freesound: {len(pairs):,} text-audio pairs")
        return pairs


# ---------------------------------------------------------------------------
# Production Knowledge Caption Generator
# ---------------------------------------------------------------------------

class ProductionCaptionGenerator:
    """
    Generates text-audio pairs from RESONATE's own knowledge corpus.
    Uses our genre taxonomy, instrument encyclopedia, production techniques,
    and music theory knowledge to create rich, domain-specific captions.
    """

    def __init__(self):
        self._genre_taxonomy = None
        self._instruments = None
        self._techniques = None
        self._theory = None

    def _load_knowledge(self):
        """Load RESONATE knowledge modules."""
        try:
            from ml.training.knowledge.genre_taxonomy import GENRE_TAXONOMY
            self._genre_taxonomy = GENRE_TAXONOMY
        except ImportError:
            self._genre_taxonomy = {}

        try:
            from ml.training.knowledge.instruments import INSTRUMENT_FAMILIES
            self._instruments = INSTRUMENT_FAMILIES
        except ImportError:
            self._instruments = {}

        try:
            from ml.training.knowledge.production_techniques import PRODUCTION_TECHNIQUES
            self._techniques = PRODUCTION_TECHNIQUES
        except ImportError:
            self._techniques = {}

        try:
            from ml.training.knowledge.music_theory import MUSIC_THEORY
            self._theory = MUSIC_THEORY
        except ImportError:
            self._theory = {}

    def generate_captions_for_samples(self, samples: list) -> list[TextAudioPair]:
        """Generate text captions for existing audio samples using knowledge."""
        if not self._genre_taxonomy:
            self._load_knowledge()

        pairs = []
        for sample in samples:
            caption_parts = []

            # Role-based caption
            role = getattr(sample, "role", None)
            if role is not None:
                role_names = {
                    0: "kick drum", 1: "snare drum", 2: "clap",
                    3: "hi-hat", 4: "percussion", 5: "bass",
                    6: "lead synth", 7: "pad", 8: "sound effect",
                    9: "texture", 10: "vocal",
                }
                role_name = role_names.get(role, "unknown")
                caption_parts.append(f"A {role_name} sample")

            # Genre context
            genre = getattr(sample, "genre", None)
            if genre:
                caption_parts.append(f"in the style of {genre}")

            # BPM
            bpm = getattr(sample, "bpm", None)
            if bpm and bpm > 0:
                caption_parts.append(f"at {bpm:.0f} BPM")

            # Key
            key = getattr(sample, "key", None)
            if key:
                caption_parts.append(f"in the key of {key}")

            if caption_parts:
                caption = " ".join(caption_parts)
                pairs.append(TextAudioPair(
                    audio_path=getattr(sample, "filepath", ""),
                    caption=caption,
                    source="resonate_knowledge",
                    tags=[],
                ))

        logger.info(f"  Generated {len(pairs):,} knowledge-enriched captions")
        return pairs


# ---------------------------------------------------------------------------
# Master Pipeline
# ---------------------------------------------------------------------------

class PhaseEPipeline:
    """
    Master pipeline for Phase E contrastive data.
    Orchestrates all downloaders and builds the unified text-audio dataset.
    """

    def __init__(self, data_root: Path = DEFAULT_DATA_ROOT, freesound_api_key: str = ""):
        self.data_root = data_root
        self.data_root.mkdir(parents=True, exist_ok=True)
        self.freesound_api_key = freesound_api_key

        # State DB for tracking downloads
        self.db_path = data_root / "phase_e_state.db"
        self._init_db()

    def _init_db(self):
        conn = sqlite3.connect(str(self.db_path))
        conn.execute("""
            CREATE TABLE IF NOT EXISTS pairs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                audio_path TEXT,
                caption TEXT,
                source TEXT,
                duration REAL,
                tags TEXT,
                downloaded INTEGER DEFAULT 0
            )
        """)
        conn.execute("CREATE INDEX IF NOT EXISTS idx_source ON pairs(source)")
        conn.commit()
        conn.close()

    def download_all_metadata(self) -> dict[str, int]:
        """Download metadata for all Phase E sources."""
        stats = {}

        # WavCaps
        logger.info("Downloading WavCaps metadata...")
        wc = WavCapsDownloader(self.data_root)
        wc_meta = wc.download_metadata()
        total_wc = sum(len(v) for v in wc_meta.values())
        stats["wavcaps"] = total_wc

        # MusicCaps
        logger.info("Downloading MusicCaps metadata...")
        mc = MusicCapsDownloader(self.data_root)
        mc_entries = mc.download_metadata()
        stats["musiccaps"] = len(mc_entries)

        # LP-MusicCaps
        logger.info("Downloading LP-MusicCaps metadata...")
        lp = LPMusicCapsDownloader(self.data_root)
        lp_entries = lp.download_metadata()
        stats["lp_musiccaps"] = len(lp_entries)

        # AudioSet
        logger.info("Downloading AudioSet metadata and ontology...")
        aset = AudioSetDownloader(self.data_root)
        aset.download_ontology()
        segments = aset.download_segment_csvs()
        total_as = sum(len(v) for v in segments.values())
        stats["audioset"] = total_as

        logger.info(f"\nPhase E metadata summary:")
        for source, count in stats.items():
            logger.info(f"  {source}: {count:,}")
        logger.info(f"  TOTAL: {sum(stats.values()):,}")

        return stats

    def download_audio(self, max_per_source: int = 0) -> dict[str, int]:
        """Download audio for all sources. Expensive — use wisely."""
        stats = {}

        # WavCaps audio (direct download, most accessible)
        logger.info("Downloading WavCaps audio...")
        wc = WavCapsDownloader(self.data_root)
        wc_meta = wc.download_metadata()
        wc_pairs = wc.download_audio(wc_meta, max_per_source=max_per_source)
        stats["wavcaps"] = len(wc_pairs)

        # MusicCaps audio (requires yt-dlp)
        logger.info("Downloading MusicCaps audio (via yt-dlp)...")
        mc = MusicCapsDownloader(self.data_root)
        mc_entries = mc.download_metadata()
        mc_pairs = mc.download_audio(mc_entries, max_entries=max_per_source)
        stats["musiccaps"] = len(mc_pairs)

        # AudioSet audio (requires yt-dlp, very large)
        logger.info("Downloading AudioSet audio (via yt-dlp)...")
        aset = AudioSetDownloader(self.data_root)
        aset.download_ontology()
        segments = aset.download_segment_csvs()
        as_pairs = aset.segments_to_pairs(segments)
        as_downloaded = aset.download_audio_batch(as_pairs, max_clips=max_per_source)
        stats["audioset"] = len(as_downloaded)

        # Freesound (requires API key)
        if self.freesound_api_key:
            logger.info("Downloading Freesound audio...")
            fs = FreesoundDownloader(self.freesound_api_key, self.data_root)
            # Search for music production sounds
            queries = [
                "drum loop", "bass", "synth pad", "vocal chop", "hi hat",
                "808", "snare", "kick drum", "piano chord", "guitar riff",
                "ambient texture", "risers", "impacts", "foley", "orchestra",
            ]
            all_sounds = []
            for q in queries:
                sounds = fs.search_sounds(query=q, max_pages=10)
                all_sounds.extend(sounds)
            fs_pairs = fs.download_sounds(all_sounds, max_sounds=max_per_source)
            stats["freesound"] = len(fs_pairs)

        logger.info(f"\nPhase E audio download summary:")
        for source, count in stats.items():
            logger.info(f"  {source}: {count:,}")
        logger.info(f"  TOTAL: {sum(stats.values()):,}")

        return stats


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    )

    parser = argparse.ArgumentParser(description="RESONATE Phase E: Contrastive Data Pipeline")
    parser.add_argument("--data-root", default=str(DEFAULT_DATA_ROOT), help="Data root directory")
    parser.add_argument("--metadata-only", action="store_true", help="Only download metadata")
    parser.add_argument("--max-per-source", type=int, default=0, help="Max clips per source (0=all)")
    parser.add_argument("--freesound-key", default="", help="Freesound API key")
    args = parser.parse_args()

    pipeline = PhaseEPipeline(
        data_root=Path(args.data_root),
        freesound_api_key=args.freesound_key,
    )

    if args.metadata_only:
        pipeline.download_all_metadata()
    else:
        pipeline.download_all_metadata()
        pipeline.download_audio(max_per_source=args.max_per_source)
